language: go

go:
  - 1.15.x

matrix:
  include:
    - os: osx

    - os: linux
      dist: bionic

    - os: linux
      dist: focal

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:tonimelisma/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install libvips-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vips; fi